const gulp = require('gulp')
require('./clean')
require('./start-server')
require('./readme')
require('./overview')
require('./directorates')
require('./functions')
require('./next-steps')
require('./sitemap')
require('./accessibility-statement')
require('./filters-compliant-services')
require('./filters-high-risk-services')
require('./filters-medium-risk-services')
require('./filters-low-risk-services')
require('./filters-citizen-facing-services')
require('./filters-staff-facing-services')
require('./filters-sunsetting-services')
require('./filters-no-plans-for-compliance')
require('./filters')
require('./zip')
require('../export-tasks/_export')
require('./process-exit')

gulp.task('build', gulp.series([
  'sass',
  'build:clean',
  'build:start-server',
  'build:readme',
  'build:overview',
  'build:directorates',
  'build:functions',
  'build:next-steps',
  'build:sitemap',
  'build:accessibility-statement',
  'build:filters',
  'build:zip',
  'export:excel',
  'build:process-exit'
]))
